### ISSUE TITLE
Support `HttpContext` on Slices

### ISSUE THREAD

**Issue by madeyoga** [DamianEdwards/RazorSlices#22]
Support `HttpContext` on slices when used in the context of a request (e.g. on `RazorSliceHttpResult`)

**Comment by DamianEdwards** [comment]
I was thinking about this the other day actually. We could support it via the standard `@inject HttpContext` approach and just special-case properties of that type so that the context is set directly rather than via the `IServiceProvider`, or we could just add an `HttpContext?` property to the `RazorSliceHttpResult` base class and set it in the `IResult.Execute` method. I think I prefer the simplicity of the latter.
