### ISSUE TITLE
Project Still alive

### ISSUE THREAD

**Issue by jtsom** [DamianEdwards/RazorSlices#36]
Just wondering if this project is still alive, or there are plans to keep it going. Looks like a very useful library and would be very useful in a furture app, but it it dies, I don't want to depend on it.

Thanks

**Comment by DamianEdwards** [comment]
It's as alive as any other single-maintainer library 😃 
I'm actively working on adding trimming & native AOT support. But this is OSS, there's no guarantees I'll keep working on it. But you can always fork it and maintain it yourself if that happens.

**Comment by garrettlondon1** [comment]
Hi @DamianEdwards will there be an example using RazorComponentResult in .NET 8?

**Comment by DamianEdwards** [comment]
@garrettlondon1 not in this repo. This is adjacent to Razor Components. Razor Components use stateful rendering in order to enable the features of Blazor but that comes with a cost (memory, processing, etc.). Razor Slices are optimized for a different set of trade-offs with forward-only, unbuffered rendering.
